import { motion } from 'framer-motion'
import { BadgeCheck, MessagesSquare, ReceiptText, Zap } from 'lucide-react'

const FEATURES = [
  {
    icon: ReceiptText,
    title: 'Fewer mistakes',
    text: 'Every order arrives as a structured slip — items, quantities, totals, address — generated by the store, not typed from memory. Nothing gets misread at 7 AM.',
  },
  {
    icon: Zap,
    title: 'Faster deals',
    text: 'No back-and-forth negotiating the menu in chat. Customers build the order themselves; you just confirm. Average checkout: 40 seconds.',
  },
  {
    icon: BadgeCheck,
    title: 'Paid before you bake',
    text: 'Card and mobile-money payments settle online, so "is this order real?" disappears. Pay-on-delivery stays an option — your call.',
  },
  {
    icon: MessagesSquare,
    title: 'Customers stay in chat',
    text: 'The order lands in the same WhatsApp thread you already use. History, address and payment proof — all in one place, forever searchable.',
  },
]

export default function WhySection() {
  return (
    <section id="why" className="scroll-mt-24 bg-espresso py-16 text-cream sm:py-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <div className="grid items-start gap-10 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="lg:sticky lg:top-28">
            <p className="text-xs font-extrabold uppercase tracking-[0.22em] text-wa">Why chat orders win</p>
            <h2 className="mt-3 font-display text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">
              Fewer mistakes.
              <br />
              Faster deals.
              <br />
              <span className="text-cream/60">Happier regulars.</span>
            </h2>
            <p className="mt-5 max-w-md text-[15.5px] font-medium leading-relaxed text-cream/65">
              Phone calls interrupt the oven. DMs get buried. Handwritten orders
              get misread. A web store that talks to WhatsApp fixes all three —
              and keeps the conversation where your customers already live.
            </p>

            <div className="mt-8 flex gap-6">
              {[
                ['−92%', 'order errors'],
                ['2×', 'orders per day'],
                ['40s', 'to checkout'],
              ].map(([k, v]) => (
                <div key={v}>
                  <p className="font-display text-3xl font-semibold text-wa">{k}</p>
                  <p className="mt-1 text-xs font-bold uppercase tracking-wide text-cream/50">{v}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            {FEATURES.map(({ icon: Icon, title, text }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 26 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ delay: (i % 2) * 0.1 + Math.floor(i / 2) * 0.08, duration: 0.55 }}
                className={`rounded-3xl border border-white/10 bg-white/[0.06] p-6 backdrop-blur transition hover:border-wa/40 hover:bg-white/[0.09] ${
                  i % 2 === 1 ? 'sm:translate-y-6' : ''
                }`}
              >
                <span className="grid h-11 w-11 place-items-center rounded-xl bg-wa text-wa-ink">
                  <Icon className="h-5 w-5" />
                </span>
                <h3 className="mt-4 font-display text-xl font-semibold">{title}</h3>
                <p className="mt-2 text-sm font-medium leading-relaxed text-cream/65">{text}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
